
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MAJOR_CIV', 'CCB_EARLY_SETTLER_NAVIGATION');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_EARLY_SETTLER_NAVIGATION', 'MODIFIER_PLAYER_ADJUST_EMBARK_UNIT_PASS', 0, 0, 0, 'BBG_UTILS_PLAYER_HAS_TECH_SAILING', NULL);
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_EARLY_SETTLER_NAVIGATION', 'UnitType', 'UNIT_SETTLER');
