-- Leader
-- luu remove
DELETE FROM LeaderTraits WHERE LeaderType='LEADER_LEU_SANMARTIN' AND TraitType='TRAIT_LEADER_UNIT_LEU_GRANADERO';

-- all units get ability
UPDATE Modifiers SET SubjectRequirementSetId=NULL WHERE ModifierId IN ('LEU_SANMARTIN_MOUNTED_GENERALS_ATTACH', 'LEU_SANMARTIN_MOUNTED_MUSICIANS_ATTACH','LEU_SANMARTIN_MOUNTED_GENERALS','LEU_SANMARTIN_MOUNTED_MUSICIANS');

-- general and musician gpp nurf to +3
UPDATE ModifierArguments SET Value=3 WHERE Name='Amount' AND ModifierId='LEU_SANMARTIN_MOUNTED_GENERALS';
UPDATE ModifierArguments SET Value=3 WHERE Name='Amount' AND ModifierId='LEU_SANMARTIN_MOUNTED_MUSICIANS';

-- promote melee, ranged and rock band units won't finish turn
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_LEU_SANMARTIN', 'CCB_SANMARTIN_PROMOTE_NO_END_TURN');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_SANMARTIN_PROMOTE_NO_END_TURN', 'MODIFIER_PLAYER_UNITS_PROMOTE_NO_FINISH_MOVES', 0, 0, 0, NULL, 'REQSET_CCB_ARGENTINA_UNIT_IS_MELEE_RANGED_ROCK_BAND');
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_SANMARTIN_PROMOTE_NO_END_TURN', 'NoFinishMoves', '1');

INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_CCB_ARGENTINA_UNIT_IS_MELEE_RANGED_ROCK_BAND', 'REQUIREMENTSET_TEST_ANY');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_CCB_ARGENTINA_UNIT_IS_MELEE_RANGED_ROCK_BAND', 'REQ_CCB_ARGENTINA_UNIT_IS_MELEE'), 
('REQSET_CCB_ARGENTINA_UNIT_IS_MELEE_RANGED_ROCK_BAND', 'REQ_CCB_ARGENTINA_UNIT_IS_RANGED'), 
('REQSET_CCB_ARGENTINA_UNIT_IS_MELEE_RANGED_ROCK_BAND', 'REQ_CCB_ARGENTINA_UNIT_IS_ROCK_BAND');
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_CCB_ARGENTINA_UNIT_IS_MELEE', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES'), 
('REQ_CCB_ARGENTINA_UNIT_IS_RANGED', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES'), 
('REQ_CCB_ARGENTINA_UNIT_IS_ROCK_BAND', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_CCB_ARGENTINA_UNIT_IS_MELEE', 'UnitPromotionClass', 'PROMOTION_CLASS_MELEE'), 
('REQ_CCB_ARGENTINA_UNIT_IS_RANGED', 'UnitPromotionClass', 'PROMOTION_CLASS_RANGED'), 
('REQ_CCB_ARGENTINA_UNIT_IS_ROCK_BAND', 'UnitPromotionClass', 'PROMOTION_CLASS_ROCK_BAND');

-- Civilization
-- bias
UPDATE StartBiasResources SET Tier=3 WHERE CivilizationType='CIVILIZATION_LEU_ARGENTINA' AND ResourceType='RESOURCE_HORSES';
INSERT INTO StartBiasResources (CivilizationType, ResourceType, Tier) VALUES ('CIVILIZATION_LEU_ARGENTINA', 'RESOURCE_SHEEP', 3);
DELETE FROM StartBiasRivers WHERE CivilizationType='CIVILIZATION_LEU_ARGENTINA';
DELETE FROM StartBiasTerrains WHERE CivilizationType='CIVILIZATION_LEU_ARGENTINA';

-- remove old la
DELETE FROM TraitModifiers WHERE ModifierId IN ('LEU_ARGENTINA_MUSIC_PRODUCTION', 'LEU_ARGENTINA_MUSIC_PASTURE_CITIES') AND TraitType='TRAIT_CIVILIZATION_LEU_ARGENTINA';

-- slot for palace
UPDATE ModifierArguments SET Value='BUILDING_PALACE' WHERE ModifierId='LEU_ARGENTINA_MUSIC_SLOT' AND Name='BuildingType';

-- get suz bonus of buenos aires cs
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_LEU_ARGENTINA', 'MINOR_CIV_BUENOS_AIRES_BONUS_RESOURCE_AMENITY_BONUS');

-- pasture food bonus
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_LEU_ARGENTINA', 'CCB_ARGENTINA_PASTURE_FOOD_BONUS');
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('CCB_ARGENTINA_PASTURE_FOOD_BONUS', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_UTILS_PLAYER_HAS_CIVIC_EARLY_EMPIRE_REQSET', 'PLOT_HAS_PASTURE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('CCB_ARGENTINA_PASTURE_FOOD_BONUS', 'YieldType', 'YIELD_FOOD'),
('CCB_ARGENTINA_PASTURE_FOOD_BONUS', 'Amount', '1');

-- adjacency bonus for pasture
INSERT OR IGNORE INTO Ruivo_New_Adjacency
(ID, DistrictType, ProvideType, YieldType, YieldChange, AdjacencyType, CustomAdjacentObject,DistrictModifiers, TraitType, ModifierOwner, WhoIsTheOwner, CollectionType, Only, FreeCompose)VALUES 
('CCB_ARGENTINE_DISTRICT_CAMPUS_YIELD_SCIENCE_FROM_PASTURE', 'DISTRICT_CAMPUS', 'SelfBonus', 'YIELD_SCIENCE', 1, 'FROM_RINGS_CAO_IMPROVEMENT', 'IMPROVEMENT_PASTURE', 0, 'TRAIT_CIVILIZATION_LEU_ARGENTINA', 'DistrictModifiers', NULL, 'COLLECTION_CITY_DISTRICTS', 'Human&AI', 0),
('CCB_ARGENTINE_DISTRICT_THEATER_YIELD_CULTURE_FROM_PASTURE', 'DISTRICT_THEATER', 'SelfBonus', 'YIELD_CULTURE', 1, 'FROM_RINGS_CAO_IMPROVEMENT', 'IMPROVEMENT_PASTURE', 0, 'TRAIT_CIVILIZATION_LEU_ARGENTINA', 'DistrictModifiers', NULL, 'COLLECTION_CITY_DISTRICTS', 'Human&AI', 0),
('CCB_ARGENTINE_DISTRICT_INDUSTRIAL_ZONE_YIELD_PRODUCTION_FROM_PASTURE', 'DISTRICT_INDUSTRIAL_ZONE', 'SelfBonus', 'YIELD_PRODUCTION', 1, 'FROM_RINGS_CAO_IMPROVEMENT', 'IMPROVEMENT_PASTURE', 0, 'TRAIT_CIVILIZATION_LEU_ARGENTINA', 'DistrictModifiers', NULL, 'COLLECTION_CITY_DISTRICTS', 'Human&AI', 0),
('CCB_ARGENTINE_DISTRICT_HOLY_SITE_YIELD_FAITH_FROM_PASTURE', 'DISTRICT_HOLY_SITE', 'SelfBonus', 'YIELD_FAITH', 1, 'FROM_RINGS_CAO_IMPROVEMENT', 'IMPROVEMENT_PASTURE', 0, 'TRAIT_CIVILIZATION_LEU_ARGENTINA', 'DistrictModifiers', NULL, 'COLLECTION_CITY_DISTRICTS', 'Human&AI', 0);

INSERT OR IGNORE INTO Ruivo_New_Adjacency_Text (ID, Tooltip) VALUES
('CCB_ARGENTINE_DISTRICT_CAMPUS_YIELD_SCIENCE_FROM_PASTURE', 'LOC_CCB_ARGENTINE_DISTRICT_CAMPUS_YIELD_SCIENCE_FROM_PASTURE_DESCRIPTION'),
('CCB_ARGENTINE_DISTRICT_THEATER_YIELD_CULTURE_FROM_PASTURE', 'LOC_CCB_ARGENTINE_DISTRICT_THEATER_YIELD_CULTURE_FROM_PASTURE_DESCRIPTION'),
('CCB_ARGENTINE_DISTRICT_INDUSTRIAL_ZONE_YIELD_PRODUCTION_FROM_PASTURE', 'LOC_CCB_ARGENTINE_DISTRICT_INDUSTRIAL_ZONE_YIELD_PRODUCTION_FROM_PASTURE_DESCRIPTION'),
('CCB_ARGENTINE_DISTRICT_HOLY_SITE_YIELD_FAITH_FROM_PASTURE', 'LOC_CCB_ARGENTINE_DISTRICT_HOLY_SITE_YIELD_FAITH_FROM_PASTURE_DESCRIPTION');

-- musician gpp bonus
-- campus
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_CIVILIZATION_LEU_ARGENTINA', 'CCB_ARGENTINA_MUSIC_GPP_DISTRICT_CAMPUS');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_CAMPUS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'REQSET_CCB_ARGENTINA_DISTRICT_CAMPUS_ADJACENT_TO_PASTURE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_CAMPUS', 'Amount', '1'), 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_CAMPUS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_CAMPUS_ADJACENT_TO_PASTURE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_CAMPUS_ADJACENT_TO_PASTURE', 'REQ_CCB_ARGENTINA_DISTRICT_CAMPUS'), 
('REQSET_CCB_ARGENTINA_DISTRICT_CAMPUS_ADJACENT_TO_PASTURE', 'REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_CAMPUS', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES'), 
('REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE', 'REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_CAMPUS', 'DistrictType', 'DISTRICT_CAMPUS'), 
('REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE', 'ImprovementType', 'IMPROVEMENT_PASTURE'), 
('REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE', 'MaxRange', '1'), 
('REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE', 'MinRange', '1');

-- entertainment complex
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_CIVILIZATION_LEU_ARGENTINA', 'CCB_ARGENTINA_MUSIC_GPP_DISTRICT_ENTERTAINMENT_COMPLEX');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_ENTERTAINMENT_COMPLEX', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'REQSET_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX_ADJACENT_TO_PASTURE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_ENTERTAINMENT_COMPLEX', 'Amount', '1'), 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_ENTERTAINMENT_COMPLEX', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX_ADJACENT_TO_PASTURE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX_ADJACENT_TO_PASTURE', 'REQ_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX'), 
('REQSET_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX_ADJACENT_TO_PASTURE', 'REQ_CCB_ARGENTINA_ADJACENT_TO_PASTURE');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_ENTERTAINMENT_COMPLEX', 'DistrictType', 'DISTRICT_ENTERTAINMENT_COMPLEX');

-- industrial zone
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_CIVILIZATION_LEU_ARGENTINA', 'CCB_ARGENTINA_MUSIC_GPP_DISTRICT_INDUSTRIAL_ZONE');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_INDUSTRIAL_ZONE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'REQSET_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE_ADJACENT_TO_PASTURE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_INDUSTRIAL_ZONE', 'Amount', '1'), 
('CCB_ARGENTINA_MUSIC_GPP_DISTRICT_INDUSTRIAL_ZONE', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE_ADJACENT_TO_PASTURE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE_ADJACENT_TO_PASTURE', 'REQ_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQ_CCB_ARGENTINA_DISTRICT_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE');

-- ud unlock early
UPDATE Districts SET PrereqCivic='CIVIC_MEDIEVAL_FAIRES' WHERE DistrictType='DISTRICT_LEU_ARRABAL';

-- ud musician gpp remove
DELETE FROM District_GreatPersonPoints WHERE DistrictType='DISTRICT_LEU_ARRABAL' AND GreatPersonClassType='GREAT_PERSON_CLASS_MUSICIAN';

-- uu replace
DELETE FROM Units WHERE UnitType='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO Units (UnitType, BaseMoves, Cost, StrategicResource, AdvisorType, BaseSightRange, ZoneOfControl, Domain, FormationClass, Name, Description, MandatoryObsoleteTech, PurchaseYield, PromotionClass, Maintenance, Combat, RangedCombat, AirSlots, Range, PrereqTech, PrereqCivic, TraitType, BuildCharges) SELECT
'UNIT_LEU_GAUCHO', 4, Cost, 'RESOURCE_NITER', AdvisorType, BaseSightRange, ZoneOfControl, Domain, FormationClass, 'LOC_UNIT_LEU_GAUCHO_NAME', 'LOC_UNIT_LEU_GAUCHO_DESCRIPTION', MandatoryObsoleteTech, PurchaseYield, PromotionClass, Maintenance, 85, RangedCombat, AirSlots, Range, NULL, 'CIVIC_MOBILIZATION', 'TRAIT_CIVILIZATION_UNIT_LEU_GAUCHO', BuildCharges
FROM Units WHERE UnitType='UNIT_INFANTRY';

-- UnitUpgrades
DELETE FROM UnitUpgrades WHERE Unit='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO UnitUpgrades (Unit, UpgradeUnit)
SELECT 'UNIT_LEU_GAUCHO', UpgradeUnit
FROM UnitUpgrades WHERE Unit='UNIT_INFANTRY';

-- Units_XP2
DELETE FROM Units_XP2 WHERE UnitType='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO Units_XP2 (UnitType, ResourceMaintenanceAmount, ResourceCost, ResourceMaintenanceType)
SELECT 'UNIT_LEU_GAUCHO', ResourceMaintenanceAmount, ResourceCost, 'RESOURCE_NITER'
FROM Units_XP2 WHERE UnitType='UNIT_INFANTRY'; 

-- TypeTags
DELETE FROM TypeTags WHERE Type='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO TypeTags (Type, Tag) SELECT
'UNIT_LEU_GAUCHO', Tag
FROM TypeTags WHERE Type='UNIT_INFANTRY';

-- UnitAiInfos
DELETE FROM UnitAiInfos WHERE UnitType='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO UnitAiInfos (UnitType, AiType) SELECT
'UNIT_LEU_GAUCHO', AiType
FROM UnitAiInfos WHERE UnitType='UNIT_INFANTRY';

-- UnitReplaces
DELETE FROM UnitReplaces WHERE CivUniqueUnitType='UNIT_LEU_GAUCHO';
INSERT OR REPLACE INTO UnitReplaces (CivUniqueUnitType, ReplacesUnitType) VALUES
('UNIT_LEU_GAUCHO', 'UNIT_INFANTRY');

-- unique unit ability: ignore zoc
INSERT OR REPLACE INTO Tags (Tag, Vocabulary) VALUES
('CLASS_CCB_ARGENTINE_INFANTRY', 'ABILITY_CLASS');
INSERT OR REPLACE INTO TypeTags (Type, Tag) VALUES
('UNIT_LEU_GAUCHO', 'CLASS_CCB_ARGENTINE_INFANTRY'),
('ABILITY_IGNORE_ZOC', 'CLASS_CCB_ARGENTINE_INFANTRY');

-- -5 combat from general
INSERT INTO Types(Type, Kind) VALUES
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT', 'CLASS_CCB_ARGENTINE_INFANTRY');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_AOE', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 0, 0, 0, NULL, 'REQSET_CCB_SANMARTIN_AOE');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQSET_CCB_SANMARTIN_AOE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQSET_CCB_SANMARTIN_AOE', 'AOE_REQUIRES_OWNER_ADJACENCY');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_AOE', 'AbilityType', 'CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT');

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT', 'LOC_CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_NAME', 'LOC_CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_DESC', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES 
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT', 'CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_MOD');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_MOD', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_MOD', 'Amount', '-5');
INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES('CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_MOD', 'Preview', 'LOC_CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_MOD_DESC');

INSERT INTO GreatPersonIndividualBirthModifiers (GreatPersonIndividualType, ModifierId) SELECT
GreatPersonIndividualType, 'CCB_SANMARTIN_MOUNTED_GENERAL_COMBAT_AOE'
FROM GreatPersonIndividuals
WHERE GreatPersonClassType='GREAT_PERSON_CLASS_GENERAL' AND EraType IN ('ERA_INDUSTRIAL', 'ERA_MODERN');