------------------------------------------------------------------------------
--	FILE:	 new_bbg_policies.sql
--	AUTHOR:  iElden, D. / Jack The Narrator
--	PURPOSE: Database modifications by new BBG
------------------------------------------------------------------------------


-- === Existing Policies Adjustments ===
-- Buff Discipline +5 -> +10
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='DISCIPLINE_BARBARIANCOMBAT' AND Name='Amount';

-- Bastillon ""bugfix"" (Value is doubled, so put 2*+3 instead of 2*+5)
UPDATE ModifierArguments SET Value='3' WHERE ModifierId='BASTIONS_RANGEDSTRIKE' AND Name='Amount';
-- 02/07/24 Bastion ranged strength removed
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_BASTIONS' AND ModifierId='BASTIONS_RANGEDSTRIKE';

-- Communications Office give 2 Loyalty per governor promotion (from +1)
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='COMMUNICATIONS_OFFICE_GOVERNOR_IDENTITY_PER_TITLE' AND Name='Amount';

-- LIMES
-- Limes to 50%
UPDATE ModifierArguments SET Value='50' WHERE Name='Amount' AND ModifierId IN (
    SELECT ModifierId FROM PolicyModifiers WHERE PolicyType='POLICY_LIMES'
);
-- Limes doesn't Obsolete
DELETE FROM ObsoletePolicies WHERE PolicyType='POLICY_LIMES';

-- Move infantry card
UPDATE Policies SET PrereqCivic='CIVIC_MOBILIZATION' WHERE PolicyType='POLICY_MILITARY_FIRST';

-- === New Policies ===
INSERT INTO Types(Type, Kind) VALUES
	('POLICY_SIEGE', 'KIND_POLICY'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'KIND_POLICY'),
	('POLICY_TRENCH_WARFARE', 'KIND_POLICY');

INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_SIEGE', 'LOC_POLICY_SIEGE_NAME', 'LOC_POLICY_SIEGE_DESCRIPTION', 'CIVIC_MILITARY_TRAINING', 'SLOT_MILITARY'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'LOC_POLICY_HARD_SHELL_EXPLOSIVES_NAME', 'LOC_POLICY_HARD_SHELL_EXPLOSIVES_DESCRIPTION', 'CIVIC_MEDIEVAL_FAIRES', 'SLOT_MILITARY'),
	('POLICY_TRENCH_WARFARE', 'LOC_POLICY_TRENCH_WARFARE_NAME', 'LOC_POLICY_TRENCH_WARFARE_DESCRIPTION', 'CIVIC_SCORCHED_EARTH', 'SLOT_MILITARY');
	
INSERT OR IGNORE INTO ObsoletePolicies(PolicyType, ObsoletePolicy) VALUES
	('POLICY_SIEGE', 'POLICY_HARD_SHELL_EXPLOSIVES'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'POLICY_TRENCH_WARFARE');
	
INSERT OR IGNORE INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_SIEGE', 'SIEGE_ANCIENT_SIEGE_PRODUCTION'),
	('POLICY_SIEGE', 'SIEGE_CLASSICAL_SIEGE_PRODUCTION'),
    ('POLICY_SIEGE', 'SIEGE_MEDIEVAL_SIEGE_PRODUCTION'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'HARD_SHELL_ANCIENT_SIEGE_PRODUCTION'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'HARD_SHELL_CLASSICAL_SIEGE_PRODUCTION'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'HARD_SHELL_MEDIEVAL_SIEGE_PRODUCTION'),
	('POLICY_HARD_SHELL_EXPLOSIVES', 'HARD_SHELL_RENAISSANCE_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_ANCIENT_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_CLASSICAL_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_MEDIEVAL_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_RENAISSANCE_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_INDUSTRIAL_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_MODERN_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_ATOMIC_SIEGE_PRODUCTION'),
	('POLICY_TRENCH_WARFARE', 'TRENCH_WARFARE_INFORMATION_SIEGE_PRODUCTION');
	
INSERT OR IGNORE INTO Modifiers(ModifierId, ModifierType) VALUES
	('SIEGE_ANCIENT_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('SIEGE_CLASSICAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('SIEGE_MEDIEVAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('HARD_SHELL_ANCIENT_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('HARD_SHELL_CLASSICAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('HARD_SHELL_MEDIEVAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('HARD_SHELL_RENAISSANCE_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_ANCIENT_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_CLASSICAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_MEDIEVAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_RENAISSANCE_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_INDUSTRIAL_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_MODERN_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_ATOMIC_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
	('TRENCH_WARFARE_INFORMATION_SIEGE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION');
	
INSERT OR IGNORE INTO ModifierArguments(ModifierId, Name, Value, Extra) VALUES
	('SIEGE_ANCIENT_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('SIEGE_ANCIENT_SIEGE_PRODUCTION', 'EraType', 'ERA_ANCIENT', -1 ),
	('SIEGE_ANCIENT_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('SIEGE_CLASSICAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('SIEGE_CLASSICAL_SIEGE_PRODUCTION', 'EraType', 'ERA_CLASSICAL', -1 ),
	('SIEGE_CLASSICAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('SIEGE_MEDIEVAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('SIEGE_MEDIEVAL_SIEGE_PRODUCTION', 'EraType', 'ERA_MEDIEVAL', -1 ),
	('SIEGE_MEDIEVAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('HARD_SHELL_ANCIENT_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('HARD_SHELL_ANCIENT_SIEGE_PRODUCTION', 'EraType', 'ERA_ANCIENT', -1 ),
	('HARD_SHELL_ANCIENT_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('HARD_SHELL_CLASSICAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('HARD_SHELL_CLASSICAL_SIEGE_PRODUCTION', 'EraType', 'ERA_CLASSICAL', -1 ),
	('HARD_SHELL_CLASSICAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('HARD_SHELL_MEDIEVAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('HARD_SHELL_MEDIEVAL_SIEGE_PRODUCTION', 'EraType', 'ERA_MEDIEVAL', -1 ),
	('HARD_SHELL_MEDIEVAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('HARD_SHELL_RENAISSANCE_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('HARD_SHELL_RENAISSANCE_SIEGE_PRODUCTION', 'EraType', 'ERA_RENAISSANCE', -1 ),
	('HARD_SHELL_RENAISSANCE_SIEGE_PRODUCTION', 'Amount', 50, -1),	
	('TRENCH_WARFARE_ANCIENT_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_ANCIENT_SIEGE_PRODUCTION', 'EraType', 'ERA_ANCIENT', -1 ),
	('TRENCH_WARFARE_ANCIENT_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('TRENCH_WARFARE_CLASSICAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_CLASSICAL_SIEGE_PRODUCTION', 'EraType', 'ERA_CLASSICAL', -1 ),
	('TRENCH_WARFARE_CLASSICAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('TRENCH_WARFARE_MEDIEVAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_MEDIEVAL_SIEGE_PRODUCTION', 'EraType', 'ERA_MEDIEVAL', -1 ),
	('TRENCH_WARFARE_MEDIEVAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('TRENCH_WARFARE_RENAISSANCE_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_RENAISSANCE_SIEGE_PRODUCTION', 'EraType', 'ERA_RENAISSANCE', -1 ),
	('TRENCH_WARFARE_RENAISSANCE_SIEGE_PRODUCTION', 'Amount', 50, -1),		
	('TRENCH_WARFARE_INDUSTRIAL_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_INDUSTRIAL_SIEGE_PRODUCTION', 'EraType', 'ERA_INDUSTRIAL', -1 ),
	('TRENCH_WARFARE_INDUSTRIAL_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('TRENCH_WARFARE_MODERN_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_MODERN_SIEGE_PRODUCTION', 'EraType', 'ERA_MODERN', -1 ),
	('TRENCH_WARFARE_MODERN_SIEGE_PRODUCTION', 'Amount', 50, -1),	
	('TRENCH_WARFARE_ATOMIC_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_ATOMIC_SIEGE_PRODUCTION', 'EraType', 'ERA_ATOMIC', -1 ),
	('TRENCH_WARFARE_ATOMIC_SIEGE_PRODUCTION', 'Amount', 50, -1),
	('TRENCH_WARFARE_INFORMATION_SIEGE_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_SIEGE', -1 ),
	('TRENCH_WARFARE_INFORMATION_SIEGE_PRODUCTION', 'EraType', 'ERA_INFORMATION', -1 ),
	('TRENCH_WARFARE_INFORMATION_SIEGE_PRODUCTION', 'Amount', 50, -1);	

-- 03/10/22: recon units to melee/ranged cards
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_AGOGE_ANCIENT_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_AGOGE_CLASSICAL_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_MILITARYFIRST_ATOMIC_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_MILITARYFIRST_INFORMATION_RECON_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value, Extra) VALUES
	('BBG_AGOGE_ANCIENT_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_AGOGE_ANCIENT_RECON_PRODUCTION', 'EraType', 'ERA_ANCIENT', -1 ),
	('BBG_AGOGE_ANCIENT_RECON_PRODUCTION', 'Amount', 50, -1),
	('BBG_AGOGE_CLASSICAL_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_AGOGE_CLASSICAL_RECON_PRODUCTION', 'EraType', 'ERA_CLASSICAL', -1 ),
	('BBG_AGOGE_CLASSICAL_RECON_PRODUCTION', 'Amount', 50, -1),
	('BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION', 'EraType', 'ERA_MEDIEVAL', -1 ),
	('BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION', 'Amount', 50, -1),
	('BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION', 'EraType', 'ERA_RENAISSANCE', -1 ),
	('BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION', 'Amount', 50, -1),		
	('BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION', 'EraType', 'ERA_INDUSTRIAL', -1 ),
	('BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION', 'Amount', 50, -1),
	('BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION', 'EraType', 'ERA_MODERN', -1 ),
	('BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION', 'Amount', 50, -1),	
	('BBG_MILITARYFIRST_ATOMIC_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_MILITARYFIRST_ATOMIC_RECON_PRODUCTION', 'EraType', 'ERA_ATOMIC', -1 ),
	('BBG_MILITARYFIRST_ATOMIC_RECON_PRODUCTION', 'Amount', 50, -1),
	('BBG_MILITARYFIRST_INFORMATION_RECON_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_RECON', -1 ),
	('BBG_MILITARYFIRST_INFORMATION_RECON_PRODUCTION', 'EraType', 'ERA_INFORMATION', -1 ),
	('BBG_MILITARYFIRST_INFORMATION_RECON_PRODUCTION', 'Amount', 50, -1);	

INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_AGOGE', 'BBG_AGOGE_ANCIENT_RECON_PRODUCTION'),
	('POLICY_AGOGE', 'BBG_AGOGE_CLASSICAL_RECON_PRODUCTION'),
	('POLICY_FEUDAL_CONTRACT', 'BBG_AGOGE_ANCIENT_RECON_PRODUCTION'),
	('POLICY_FEUDAL_CONTRACT', 'BBG_AGOGE_CLASSICAL_RECON_PRODUCTION'),
	('POLICY_FEUDAL_CONTRACT', 'BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION'),
	('POLICY_FEUDAL_CONTRACT', 'BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_AGOGE_ANCIENT_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_AGOGE_CLASSICAL_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_AGOGE_ANCIENT_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_AGOGE_CLASSICAL_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_FEUDALCONTRACT_MEDIEVAL_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_FEUDALCONTRACT_RENAISSANCE_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_GRANDEARMEE_INDUSTRIAL_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_GRANDEARMEE_MODERN_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_MILITARYFIRST_ATOMIC_RECON_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'BBG_MILITARYFIRST_INFORMATION_RECON_PRODUCTION');

-- 2025/09/23 all ranged prod policy effects on classical ranged units (e.g. Scythia's uu)
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_FEUDAL_CONTRACT', 'AGOGE_CLASSICAL_RANGED_PRODUCTION'),
	('POLICY_GRANDE_ARMEE', 'AGOGE_CLASSICAL_RANGED_PRODUCTION'),
	('POLICY_MILITARY_FIRST', 'AGOGE_CLASSICAL_RANGED_PRODUCTION');

-- 10/03/24 Medina +1 housing per district
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBG_MEDINA_HOUSING_DISTRICT', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 'BBG_IS_SPECIALTY_DISTRICT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_MEDINA_HOUSING_DISTRICT', 'Amount', 1);
UPDATE PolicyModifiers SET ModifierId='BBG_MEDINA_HOUSING_DISTRICT' WHERE ModifierId='MEDINAQUARTER_SPECIALTYHOUSING';

-- 28/11/24 Raj now gives +1 prod/food, +2sci/culture/faith/gold per traderoute to a city state
DELETE FROM PolicyModifiers WHERE ModifierId LIKE 'RAJ%TRIBUTARY';

INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_RAJ_CITY_TRADE_ROUTE_FOOD', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD'),
	('BBG_RAJ_CITY_TRADE_ROUTE_PROD', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD'),
	('BBG_RAJ_CITY_TRADE_ROUTE_FAITH', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD'),
	('BBG_RAJ_CITY_TRADE_ROUTE_SCIENCE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD'),
	('BBG_RAJ_CITY_TRADE_ROUTE_CULTURE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_RAJ_CITY_TRADE_ROUTE_FOOD', 'YieldType', 'YIELD_FOOD'),
	('BBG_RAJ_CITY_TRADE_ROUTE_FOOD', 'Amount', 1),
	('BBG_RAJ_CITY_TRADE_ROUTE_PROD', 'YieldType', 'YIELD_PRODUCTION'),
	('BBG_RAJ_CITY_TRADE_ROUTE_PROD', 'Amount', 1),
	('BBG_RAJ_CITY_TRADE_ROUTE_FAITH', 'YieldType', 'YIELD_FAITH'),
	('BBG_RAJ_CITY_TRADE_ROUTE_FAITH', 'Amount', 2),
	('BBG_RAJ_CITY_TRADE_ROUTE_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('BBG_RAJ_CITY_TRADE_ROUTE_SCIENCE', 'Amount', 2),
	('BBG_RAJ_CITY_TRADE_ROUTE_CULTURE', 'YieldType', 'YIELD_CULTURE'),
	('BBG_RAJ_CITY_TRADE_ROUTE_CULTURE', 'Amount', 2);

INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_RAJ', 'BBG_RAJ_CITY_TRADE_ROUTE_FOOD'),
	('POLICY_RAJ', 'BBG_RAJ_CITY_TRADE_ROUTE_PROD'),
	('POLICY_RAJ', 'BBG_RAJ_CITY_TRADE_ROUTE_FAITH'),
	('POLICY_RAJ', 'BBG_RAJ_CITY_TRADE_ROUTE_SCIENCE'),
	('POLICY_RAJ', 'BBG_RAJ_CITY_TRADE_ROUTE_CULTURE');

-- 28/11/24 Merchant Confederation/Gunboat Diplomacy/Ideology changes
-- 28/11/24 Merchant confederation obsolete at Ideology/Gunboat Diplomacy
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_MERCHANT_CONFEDERATION', 'POLICY_GUNBOAT_DIPLOMACY');
-- 28/11/24 New green card giving freedom of movement into city state at Civil, osbsolete at Ideology/Gunboat Diplomacy /!\ care if you move gunboat as it is ideology which give open borders with cs now
INSERT INTO Types(Type, Kind) VALUES
	('POLICY_SOVEREIGN_STATE', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_SOVEREIGN_STATE', 'LOC_POLICY_SOVEREIGN_STATE_NAME', 'LOC_POLICY_SOVEREIGN_STATE_DESCRIPTION', 'CIVIC_CIVIL_SERVICE', 'SLOT_DIPLOMATIC');
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_SOVEREIGN_STATE', 'POLICY_GUNBOAT_DIPLOMACY');
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_GUNBOAT_DIPLOMACY' AND ModifierId='GUNBOATDIPLOMACY_OPENBORDERS';
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_SOVEREIGN_STATE', 'GUNBOATDIPLOMACY_OPENBORDERS');
-- 28/11/24 Ideology now gives open border without card
INSERT INTO CivicModifiers (CivicType, ModifierId) VALUES
	('CIVIC_IDEOLOGY', 'GUNBOATDIPLOMACY_OPENBORDERS');
-- 28/11/24 Gunboat Diplomacy now gets Merchant confederation bonus of +4 golds (do not grant open border with cs anymore)
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_GUNBOAT_DIPLOMACY', 'MERCHANTCONFEDERATION_INFLUENCETOKENGOLD');

-- 28/11/24 Colonial Taxes/Offices changes
-- 28/11/24 both cards now work for cities 8+ tiles away from cap and not based on continent
UPDATE Modifiers SET SubjectRequirementSetId='BBG_IS_PLOT_8_TILES_OR_MORE_FROM_CAPITAL_REQUIREMENTS' WHERE ModifierId IN ('COLONIALOFFICES_FOREIGNGROWTH', 'COLONIALTAXES_FOREIGNGOLD', 'COLONIALOFFICES_FOREIGNIDENTITY', 'COLONIALTAXES_FOREIGNPRODUCTION');
-- 28/11/24 offices is obsolete when taxes is unlocked
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_COLONIAL_OFFICES', 'POLICY_COLONIAL_TAXES');
-- 28/11/24 offices also gives production
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_COLONIAL_OFFICES', 'COLONIALTAXES_FOREIGNPRODUCTION');

-- 15/12/24 Veterancy now obsolete at mobi replaced by arms race that also give production to aerodrome and its building
INSERT INTO Types(Type, Kind) VALUES
	('POLICY_ARMS_RACE', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_ARMS_RACE', 'LOC_POLICY_ARMS_RACE_NAME', 'LOC_POLICY_ARMS_RACE_DESCRIPTION', 'CIVIC_MOBILIZATION', 'SLOT_MILITARY');
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_VETERANCY', 'POLICY_ARMS_RACE');

INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_ARMS_RACE_AERODROME_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
	('BBG_ARMS_RACE_AERODROME_BUILDING_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_ARMS_RACE_AERODROME_PRODUCTION', 'DistrictType', 'DISTRICT_AERODROME'),
	('BBG_ARMS_RACE_AERODROME_PRODUCTION', 'Amount', '30'),
	('BBG_ARMS_RACE_AERODROME_BUILDING_PRODUCTION', 'DistrictType', 'DISTRICT_AERODROME'),
	('BBG_ARMS_RACE_AERODROME_BUILDING_PRODUCTION', 'Amount', '30');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_ARMS_RACE', 'BBG_ARMS_RACE_AERODROME_PRODUCTION'),
	('POLICY_ARMS_RACE', 'BBG_ARMS_RACE_AERODROME_BUILDING_PRODUCTION'),
	('POLICY_ARMS_RACE', 'VETERANCY_ENCAMPMENT_PRODUCTION'),
	('POLICY_ARMS_RACE', 'VETERANCY_ENCAMPMENT_BUILDINGS_PRODUCTION'),
	('POLICY_ARMS_RACE', 'VETERANCY_HARBOR_PRODUCTION'),
	('POLICY_ARMS_RACE', 'VETERANCY_HARBOR_BUILDINGS_PRODUCTION');


-- 30/03/25 Defense of the motherland now on Ideology and no longers needs Communism
UPDATE Policies SET PrereqCivic='CIVIC_IDEOLOGY' WHERE PolicyType='POLICY_DEFENSE_OF_MOTHERLAND';
DELETE FROM Policy_GovernmentExclusives_XP2 WHERE PolicyType='POLICY_DEFENSE_OF_MOTHERLAND';
	

-- 30/06/25 New red card : +10 regen for land units per turn outside of friendly territory.
INSERT INTO Types (Type, Kind) VALUES
	('POLICY_BATTLEFIELD_MEDICINE', 'KIND_POLICY');
INSERT INTO Policies (PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_BATTLEFIELD_MEDICINE', 'LOC_POLICY_BATTLEFIELD_MEDICINE_NAME', 'LOC_POLICY_BATTLEFIELD_MEDICINE_DESCRIPTION', 'CIVIC_MILITARY_TRAINING', 'SLOT_MILITARY');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_BATTLEFIELD_MEDICINE', 'BBG_BATTLEFIELD_MEDICINE_HEAL_NEUTRAL'),
	('POLICY_BATTLEFIELD_MEDICINE', 'BBG_BATTLEFIELD_MEDICINE_HEAL_ENEMY');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_BATTLEFIELD_MEDICINE_HEAL_NEUTRAL', 'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN'),
	('BBG_BATTLEFIELD_MEDICINE_HEAL_ENEMY', 'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_BATTLEFIELD_MEDICINE_HEAL_NEUTRAL', 'Amount', 10),
	('BBG_BATTLEFIELD_MEDICINE_HEAL_NEUTRAL', 'Type', 'NEUTRAL'),
	('BBG_BATTLEFIELD_MEDICINE_HEAL_ENEMY', 'Amount', 10),
	('BBG_BATTLEFIELD_MEDICINE_HEAL_ENEMY', 'Type', 'ENEMY');

-- 2026/02/26 Military Research : [OLD] +2 Science from Mili Academies, Seaports and Renaissance Wall 
-- [NEW] +1 Science from Armory, Shipyards, and Medieval Walls. +2 Science from Mili Academies, Seaports, Renaissance Wall, and Hangars.
-- No longer go obsolete
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('CCB_MILITARYRESEARCH_ARMORY_SCIENCE_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
    ('CCB_MILITARYRESEARCH_SHIPYARD_SCIENCE_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
    ('CCB_MILITARYRESEARCH_MEDIEVALWALLS_SCIENCE_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
    ('CCB_MILITARYRESEARCH_HANGAR_SCIENCE_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('CCB_MILITARYRESEARCH_ARMORY_SCIENCE_MODIFIER', 'BuildingType', 'BUILDING_ARMORY'),
    ('CCB_MILITARYRESEARCH_ARMORY_SCIENCE_MODIFIER', 'YieldType', 'YIELD_SCIENCE'),
    ('CCB_MILITARYRESEARCH_ARMORY_SCIENCE_MODIFIER', 'Amount', 1),
    ('CCB_MILITARYRESEARCH_SHIPYARD_SCIENCE_MODIFIER', 'BuildingType', 'BUILDING_SHIPYARD'),
    ('CCB_MILITARYRESEARCH_SHIPYARD_SCIENCE_MODIFIER', 'YieldType', 'YIELD_SCIENCE'),
    ('CCB_MILITARYRESEARCH_SHIPYARD_SCIENCE_MODIFIER', 'Amount', 1),
    ('CCB_MILITARYRESEARCH_MEDIEVALWALLS_SCIENCE_MODIFIER', 'BuildingType', 'BUILDING_CASTLE'),
    ('CCB_MILITARYRESEARCH_MEDIEVALWALLS_SCIENCE_MODIFIER', 'YieldType', 'YIELD_SCIENCE'),
    ('CCB_MILITARYRESEARCH_MEDIEVALWALLS_SCIENCE_MODIFIER', 'Amount', 1),
    ('CCB_MILITARYRESEARCH_HANGAR_SCIENCE_MODIFIER', 'BuildingType', 'BUILDING_HANGAR'),
    ('CCB_MILITARYRESEARCH_HANGAR_SCIENCE_MODIFIER', 'YieldType', 'YIELD_SCIENCE'),
    ('CCB_MILITARYRESEARCH_HANGAR_SCIENCE_MODIFIER', 'Amount', 2);
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_MILITARY_RESEARCH', 'CCB_MILITARYRESEARCH_ARMORY_SCIENCE_MODIFIER'),
    ('POLICY_MILITARY_RESEARCH', 'CCB_MILITARYRESEARCH_SHIPYARD_SCIENCE_MODIFIER'),
    ('POLICY_MILITARY_RESEARCH', 'CCB_MILITARYRESEARCH_MEDIEVALWALLS_SCIENCE_MODIFIER'),
    ('POLICY_MILITARY_RESEARCH', 'CCB_MILITARYRESEARCH_HANGAR_SCIENCE_MODIFIER');
DELETE FROM ObsoletePolicies WHERE PolicyType='POLICY_MILITARY_RESEARCH';

-- 2026/02/26 War of Religion: Become obsolete at Ideology. Receive the bonus passively at Ideology if you have reformed church unlocked.
-- /!\ Spaghetti code, as it is not replaced by a card but by a passive bonus, I have to make it obsolete from another civic that could move at some point !
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
    ('POLICY_WARS_OF_RELIGION', 'POLICY_LIGHTNING_WARFARE');

INSERT INTO Types (Type, Kind) VALUES
    ('CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY', 'CLASS_ALL_COMBAT_UNITS');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY', 'LOC_CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY_NAME', 'LOC_PROMOTION_COMBAT_WARS_OF_RELIGION', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY', 'CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_MODIFIER');
INSERT INTO CivicModifiers(CivicType, ModifierId) VALUES
    ('CIVIC_IDEOLOGY', 'CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_GIVER');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
    ('CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_GIVER', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'BBG_UTILS_PLAYER_HAS_CIVIC_REFORMED_CHURCH_REQSET', 'WARS_OF_RELIGION_REQUIREMENTS'),
    ('CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL, 'REQUIREMENTS_OPPONENT_IS_OTHER_RELIGION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_GIVER', 'AbilityType', 'CCB_ABILITY_WAR_OF_RELIGION_IDEOLOGY_ABILITY'),
    ('CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_MODIFIER', 'Amount', 4);

INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES
    ('CCB_IDEOLOGY_WAR_OF_RELIGION_COMBAT_STRENGTH_MODIFIER', 'Preview', 'LOC_PROMOTION_COMBAT_WARS_OF_RELIGION');

-- 2026/01/26 Sports Media: Now give +1 amenity in every cities (from +1 from Stadium)
UPDATE Modifiers SET SubjectRequirementSetId=NULL WHERE ModifierId='SPORTSMEDIA_STADIUMENTERTAINMENT';

-- 2026/02/26 Defense of the Motherlands: No longer remove war weariness from combat in your territory. Is now a red card.
UPDATE Policies SET GovernmentSlotType='SLOT_MILITARY' WHERE PolicyType='POLICY_DEFENSE_OF_MOTHERLAND';
DELETE FROM PolicyModifiers WHERE ModifierId='DEFENSEOFMOTHERLAND_DOMESTICWARWEARINESS' AND PolicyType='POLICY_DEFENSE_OF_MOTHERLAND';

-- 2026/02/26 Arm’s Race: Red Card, +25% toward nukes production. Unlocked at Nuclear Program.
INSERT OR IGNORE INTO Types(Type, Kind) VALUES
    ('CCB_MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'KIND_MODIFIER');
INSERT OR IGNORE INTO DynamicModifiers(ModifierType, CollectionType, EffectType) VALUES
    ('CCB_MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_PROJECT_PRODUCTION');  
INSERT INTO Types(Type, Kind) VALUES
    ('POLICY_ARMS_RACE_T', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
    ('POLICY_ARMS_RACE_T', 'LOC_POLICY_ARMS_RACE_T_NAME', 'LOC_POLICY_ARMS_RACE_T_DESCRIPTION', 'CIVIC_NUCLEAR_PROGRAM', 'SLOT_MILITARY');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('CCB_ARMS_RACE_FASTER_NUKE', 'CCB_MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION'),
    ('CCB_ARMS_RACE_FASTER_THERMO', 'CCB_MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('CCB_ARMS_RACE_FASTER_NUKE', 'ProjectType', 'PROJECT_BUILD_NUCLEAR_DEVICE'),
    ('CCB_ARMS_RACE_FASTER_NUKE', 'Amount', 25),
    ('CCB_ARMS_RACE_FASTER_THERMO', 'ProjectType', 'PROJECT_BUILD_THERMONUCLEAR_DEVICE'),
    ('CCB_ARMS_RACE_FASTER_THERMO', 'Amount', 25);
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_ARMS_RACE_T', 'CCB_ARMS_RACE_FASTER_NUKE'),
    ('POLICY_ARMS_RACE_T', 'CCB_ARMS_RACE_FASTER_THERMO');

-- 2026/05/10: policies rework
-- nation identity obsolete at totalitarism, and work auyomatically
INSERT OR IGNORE INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_NATIONAL_IDENTITY', 'POLICY_THIRD_ALTERNATIVE');
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_TOTALITARIANISM', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_NATIONAL_IDENTITY';

-- wisselbanken obsolete at suffrage, and work automatically
INSERT OR IGNORE INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_WISSELBANKEN', 'POLICY_NEW_DEAL');
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_SUFFRAGE', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_WISSELBANKEN';

-- public works and skyscrapers obsolete at class struggle, and work automatically
INSERT OR IGNORE INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_PUBLIC_WORKS', 'POLICY_COLLECTIVIZATION');
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_CLASS_STRUGGLE', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_PUBLIC_WORKS';

INSERT OR IGNORE INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_SKYSCRAPERS', 'POLICY_COLLECTIVIZATION');
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_CLASS_STRUGGLE', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_SKYSCRAPERS';

-- civic corporate libertarianism automatically act third alternative
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_CORPORATE_LIBERTARIANISM', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_THIRD_ALTERNATIVE';

-- civic digital democracy automatically act new deal
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_DIGITAL_DEMOCRACY', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_NEW_DEAL';

-- civic synthetic technocracy automatically act collectivization
INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) SELECT 
	'CIVIC_SYNTHETIC_TECHNOCRACY', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_COLLECTIVIZATION';

-- new policies
-- culture education: +4 gpp for artists, musicians and writers. +2/+2/+4 gpp for each corresponding building
INSERT INTO Types(Type, Kind) VALUES
	('POLICY_CULTURE_EDUCATION', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_CULTURE_EDUCATION', 'LOC_POLICY_CULTURE_EDUCATION_NAME', 'LOC_POLICY_CULTURE_EDUCATION_DESCRIPTION', 'CIVIC_CULTURAL_HERITAGE', 'SLOT_GREAT_PERSON');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('CCB_CULTURE_EDUCATION_ARTIST_GPP', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL),
	('CCB_CULTURE_EDUCATION_MUSICIAN_GPP', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL),
	('CCB_CULTURE_EDUCATION_WRITER_GPP', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL),
	('CCB_CULTURE_EDUCATION_ARTIST_BUILDING_GPP', 'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT', 'BUILDING_IS_MUSEUM_ART'),
	('CCB_CULTURE_EDUCATION_MUSICIAN_BUILDING_GPP', 'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT', 'BUILDING_IS_BROADCAST_CENTER'),
	('CCB_CULTURE_EDUCATION_WRITER_BUILDING_GPP', 'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT', 'BUILDING_IS_AMPHITHEATER');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('CCB_CULTURE_EDUCATION_ARTIST_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
	('CCB_CULTURE_EDUCATION_ARTIST_GPP', 'Amount', 4),
	('CCB_CULTURE_EDUCATION_MUSICIAN_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN'),
	('CCB_CULTURE_EDUCATION_MUSICIAN_GPP', 'Amount', 4),
	('CCB_CULTURE_EDUCATION_WRITER_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_WRITER'),
	('CCB_CULTURE_EDUCATION_WRITER_GPP', 'Amount', 4),
	('CCB_CULTURE_EDUCATION_ARTIST_BUILDING_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
	('CCB_CULTURE_EDUCATION_ARTIST_BUILDING_GPP', 'Amount', 2),
	('CCB_CULTURE_EDUCATION_MUSICIAN_BUILDING_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN'),
	('CCB_CULTURE_EDUCATION_MUSICIAN_BUILDING_GPP', 'Amount', 2),
	('CCB_CULTURE_EDUCATION_WRITER_BUILDING_GPP', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_WRITER'),
	('CCB_CULTURE_EDUCATION_WRITER_BUILDING_GPP', 'Amount', 4);
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_ARTIST_GPP'),
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_MUSICIAN_GPP'),
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_WRITER_GPP'),
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_ARTIST_BUILDING_GPP'),
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_MUSICIAN_BUILDING_GPP'),
	('POLICY_CULTURE_EDUCATION', 'CCB_CULTURE_EDUCATION_WRITER_BUILDING_GPP');
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_LITERARY_TRADITION', 'POLICY_CULTURE_EDUCATION'),
	('POLICY_FRESCOES', 'POLICY_CULTURE_EDUCATION'),
	('POLICY_SYMPHONIES', 'POLICY_CULTURE_EDUCATION');

-- war hospital: +20 healing for units
INSERT INTO Types(Type, Kind) VALUES
	('POLICY_WAR_HOSPITAL', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
	('POLICY_WAR_HOSPITAL', 'LOC_POLICY_WAR_HOSPITAL_NAME', 'LOC_POLICY_WAR_HOSPITAL_DESCRIPTION', 'CIVIC_MOBILIZATION', 'SLOT_MILITARY');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES 
('POLICY_WAR_HOSPITAL', 'CCB_WAR_HOSPITAL_HEALING');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_WAR_HOSPITAL_HEALING', 'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_WAR_HOSPITAL_HEALING', 'Amount', '20'), 
('CCB_WAR_HOSPITAL_HEALING', 'Type', 'ALL');

-- machiavellianism now is replaced by nuclear espionage; nuclear espionage now cover old traits of machiavellianism
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
	('POLICY_MACHIAVELLIANISM', 'POLICY_NUCLEAR_ESPIONAGE');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) SELECT
	'POLICY_NUCLEAR_ESPIONAGE', ModifierId
FROM PolicyModifiers
WHERE PolicyType='POLICY_MACHIAVELLIANISM';

-- gunboat diplomacy +25% favor
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES 
('POLICY_GUNBOAT_DIPLOMACY', 'CCB_GUNBOAT_DIPLOMACY_FAVOR');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_GUNBOAT_DIPLOMACY_FAVOR', 'MODIFIER_PLAYER_GOVERNMENT_FLAT_BONUS', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_GUNBOAT_DIPLOMACY_FAVOR', 'Amount', '25'), 
('CCB_GUNBOAT_DIPLOMACY_FAVOR', 'BonusType', 'GOVERNMENTBONUS_ENVOYS');

-- after action reports no finish moves
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES 
('POLICY_AFTER_ACTION_REPORTS', 'CCB_AFTER_ACTION_REPORTS_NO_FINISH_MOVES');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_AFTER_ACTION_REPORTS_NO_FINISH_MOVES', 'MODIFIER_PLAYER_UNITS_PROMOTE_NO_FINISH_MOVES', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_AFTER_ACTION_REPORTS_NO_FINISH_MOVES', 'NoFinishMoves', '1');

-- drill manuals: bonus to +4/+4/+2/+2
UPDATE ModifierArguments SET Value=4 WHERE ModifierId='BBG_POLICY_GIVE_FREE_COAL' AND Name='Amount';
UPDATE ModifierArguments SET Value=4 WHERE ModifierId='BBG_POLICY_GIVE_FREE_NITER' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DRILL_MANUALS_ADDITIONAL_COAL_EXTRACTION' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DRILL_MANUALS_ADDITIONAL_NITER_EXTRACTION' AND Name='Amount';

-- resource management: bonus to +4/+4/+2/+2
UPDATE ModifierArguments SET Value=4 WHERE ModifierId='BBG_POLICY_GIVE_FREE_OIL' AND Name='Amount';
UPDATE ModifierArguments SET Value=4 WHERE ModifierId='BBG_POLICY_GIVE_FREE_ALUMINUM' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='RESOURCE_MANAGEMENT_ADDITIONAL_OIL_EXTRACTION' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='RESOURCE_MANAGEMENT_ADDITIONAL_ALUMINUM_EXTRACTION' AND Name='Amount';

-- secend strike capability removed and merged into arm race t
DELETE FROM Types WHERE Type='POLICY_SECOND_STRIKE_CAPABILITY';
INSERT INTO PolicyModifiers (PolicyType, ModifierId) SELECT
	'POLICY_ARMS_RACE_T', ModifierId
FROM PolicyModifiers WHERE PolicyType='POLICY_SECOND_STRIKE_CAPABILITY';