-- Created by iElden

-- Add Ressource Bias
INSERT INTO StartBiasResources(CivilizationType, ResourceType, Tier) VALUES
    ('CIVILIZATION_CREE', 'RESOURCE_CATTLE', '4'),
    ('CIVILIZATION_CREE', 'RESOURCE_HORSES', '4'),
    ('CIVILIZATION_CREE', 'RESOURCE_SHEEP', '4'),
    ('CIVILIZATION_CREE', 'RESOURCE_DEER', '4');

-- Delete free trader (keep tradetoute capacity)
-- 2026/04/23: free trader back at civic foreign trade; get trade route capacity at tech currency and civic diplomatic service
-- UPDATE ModifierArguments SET Value='0' WHERE ModifierId='TRAIT_POTTERY_ADD_TRADER' AND Name='Amount';
UPDATE Modifiers SET OwnerRequirementSetId='REQSET_CCB_PLAYER_HAS_CIVIC_FOREIGN_TRADE_AND_CAPITAL' WHERE ModifierId='TRAIT_POTTERY_ADD_TRADER';
UPDATE Modifiers SET SubjectRequirementSetId='BBG_UTILS_PLAYER_HAS_TECH_CURRENCY' WHERE ModifierId='TRAIT_POTTERY_TRADE_ROUTE';

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_CIVILIZATION_CREE_TRADE_GAIN_TILES', 'CCB_DIPLOMATIC_SERVICE_TRADE_ROUTE');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('CCB_DIPLOMATIC_SERVICE_TRADE_ROUTE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 'BBG_UTILS_PLAYER_HAS_CIVIC_DIPLOMATIC_SERVICE_REQSET');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('CCB_DIPLOMATIC_SERVICE_TRADE_ROUTE', 'Amount', '1');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('REQSET_CCB_PLAYER_HAS_CIVIC_FOREIGN_TRADE_AND_CAPITAL', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('REQSET_CCB_PLAYER_HAS_CIVIC_FOREIGN_TRADE_AND_CAPITAL', 'BBG_UTILS_PLAYER_HAS_CIVIC_FOREIGN_TRADE_REQUIREMENT'),
    ('REQSET_CCB_PLAYER_HAS_CIVIC_FOREIGN_TRADE_AND_CAPITAL', 'REQUIRES_CAPITAL_CITY');

-- 17/04/23 Oki loses 5 base str but gain 5 against stronger units
UPDATE Units SET Combat=15 WHERE UnitType='UNIT_CREE_OKIHTCITAW';

INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType) VALUES
    ('REQUIRES_COMBAT_AGAINST_STRONGER_UNIT','REQUIREMENT_OPPONENT_IS_STRONGER');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS', 'REQUIRES_COMBAT_AGAINST_STRONGER_UNIT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBG_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'Amount', 5);

INSERT INTO Types (Type, Kind) VALUES
	('BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'CLASS_CREE_OKIHTCITAW');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description) VALUES
    ('BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'LOC_BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'LOC_BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS_DESCRIPTION');
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'BBG_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS');
INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES
    ('BBG_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS', 'Preview', 'LOC_BBG_ABILITY_OKIHTCITAW_STRONG_AGAINST_STRONGER_UNITS_DESCRIPTION');

-- 30/11/24 Ancient unit gets -5 agaisnt city center, see Base/Units.sql
INSERT INTO TypeTags (Type, Tag) VALUES
    ('UNIT_CREE_OKIHTCITAW', 'CLASS_MALUS_CITY_CENTER');