--==================
-- Zulu
--==================
-- impi come at stirrips like pikemen
-- UPDATE Units SET PrereqTech='TECH_STIRRUPS' WHERE UnitType='UNIT_ZULU_IMPI';
-- +1 culture and +1 gold for each encampment building
--INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES
--	('ZULU_BARRACKS_CULTURE_BBG', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_BARRACKS_GOLD_BBG', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_STABLE_CULTURE_BBG',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_STABLE_GOLD_BBG',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_ARMORY_CULTURE_BBG',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_ARMORY_GOLD_BBG',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_ACADEMY_CULTURE_BBG',  'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
--	('ZULU_ACADEMY_GOLD_BBG',  'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');
--INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES
--	('ZULU_BARRACKS_CULTURE_BBG', 'BuildingType', 'BUILDING_BARRACKS'),
--	('ZULU_BARRACKS_CULTURE_BBG', 'YieldType', 'YIELD_CULTURE'),
--	('ZULU_BARRACKS_CULTURE_BBG', 'Amount', '1'),
--	('ZULU_BARRACKS_GOLD_BBG',    'BuildingType', 'BUILDING_BARRACKS'),
--	('ZULU_BARRACKS_GOLD_BBG',    'YieldType', 'YIELD_GOLD'),
--	('ZULU_BARRACKS_GOLD_BBG',    'Amount', '1'),
--	('ZULU_STABLE_CULTURE_BBG',   'BuildingType', 'BUILDING_STABLE'),
--	('ZULU_STABLE_CULTURE_BBG',   'YieldType', 'YIELD_CULTURE'),
--	('ZULU_STABLE_CULTURE_BBG',   'Amount', '1'),
--	('ZULU_STABLE_GOLD_BBG',      'BuildingType', 'BUILDING_STABLE'),
--	('ZULU_STABLE_GOLD_BBG',      'YieldType', 'YIELD_GOLD'),
--	('ZULU_STABLE_GOLD_BBG',      'Amount', '1'),
--	('ZULU_ARMORY_CULTURE_BBG',   'BuildingType', 'BUILDING_ARMORY'),
--	('ZULU_ARMORY_CULTURE_BBG',   'YieldType', 'YIELD_CULTURE'),
--	('ZULU_ARMORY_CULTURE_BBG',   'Amount', '1'),
--	('ZULU_ARMORY_GOLD_BBG',      'BuildingType', 'BUILDING_ARMORY'),
--	('ZULU_ARMORY_GOLD_BBG',      'YieldType', 'YIELD_GOLD'),
--	('ZULU_ARMORY_GOLD_BBG',      'Amount', '1'),
--	('ZULU_ACADEMY_CULTURE_BBG',  'BuildingType', 'BUILDING_MILITARY_ACADEMY'),
--	('ZULU_ACADEMY_CULTURE_BBG',  'YieldType', 'YIELD_CULTURE'),
--	('ZULU_ACADEMY_CULTURE_BBG',  'Amount', '1'),
--	('ZULU_ACADEMY_GOLD_BBG',     'BuildingType', 'BUILDING_MILITARY_ACADEMY'),
--	('ZULU_ACADEMY_GOLD_BBG',     'YieldType', 'YIELD_GOLD'),
--	('ZULU_ACADEMY_GOLD_BBG',     'Amount', '1');
--INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_BARRACKS_CULTURE_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_BARRACKS_GOLD_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_STABLE_CULTURE_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_STABLE_GOLD_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_ARMORY_CULTURE_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_ARMORY_GOLD_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_ACADEMY_CULTURE_BBG'),
--	('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'ZULU_ACADEMY_GOLD_BBG');
-- Zulu get corps/armies bonus at nationalism
INSERT OR IGNORE INTO RequirementSets (RequirementSetId , RequirementSetType)
    VALUES ('PLAYER_HAS_NATIONALISM_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
    VALUES ('REQUIRES_PLAYER_HAS_NATIONALISM' , 'REQUIREMENT_PLAYER_HAS_CIVIC');
INSERT OR IGNORE INTO RequirementArguments (RequirementId , Name , Value)
    VALUES ('REQUIRES_PLAYER_HAS_NATIONALISM' , 'CivicType' , 'CIVIC_NATIONALISM');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId , RequirementId)
    VALUES ('PLAYER_HAS_NATIONALISM_REQUIREMENTS' , 'REQUIRES_PLAYER_HAS_NATIONALISM');
--UPDATE Modifiers SET SubjectRequirementSetId='PLAYER_HAS_NATIONALISM_REQUIREMENTS' WHERE ModifierId='TRAIT_LAND_CORPS_COMBAT_STRENGTH';
--UPDATE Modifiers SET SubjectRequirementSetId='PLAYER_HAS_NATIONALISM_REQUIREMENTS' WHERE ModifierId='TRAIT_LAND_ARMIES_COMBAT_STRENGTH';

-- 16/04/23 remove +3 combat bonus on nationalism (so keep only +2 on Mobilisation)
UPDATE Modifiers SET SubjectRequirementSetId='BBG_UTILS_PLAYER_HAS_CIVIC_MOBILIZATION_REQSET' WHERE ModifierId='TRAIT_LAND_CORPS_COMBAT_STRENGTH';
UPDATE Modifiers SET SubjectRequirementSetId='BBG_UTILS_PLAYER_HAS_CIVIC_MOBILIZATION_REQSET' WHERE ModifierId='TRAIT_LAND_ARMIES_COMBAT_STRENGTH';

UPDATE ModifierArguments SET Value=2 WHERE ModifierId='TRAIT_LAND_CORPS_COMBAT_STRENGTH' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='TRAIT_LAND_ARMIES_COMBAT_STRENGTH' AND Name='Amount';

-- INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_AMABUTHO', 'BBG_LAND_CORPS_COMBAT_STRENGTH_NATIONALISM'),
--     ('TRAIT_LEADER_AMABUTHO', 'BBG_LAND_ARMIES_COMBAT_STRENGTH_NATIONALISM');

-- INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
--     ('BBG_LAND_CORPS_COMBAT_STRENGTH_NATIONALISM', 'MODIFIER_PLAYER_CORPS_ARMY_MODIFIED_STRENGTH', 'BBG_ZULU_NATIONALISM_REQUIREMENTS'),
--     ('BBG_LAND_ARMIES_COMBAT_STRENGTH_NATIONALISM', 'MODIFIER_PLAYER_CORPS_ARMY_MODIFIED_STRENGTH', 'BBG_ZULU_NATIONALISM_REQUIREMENTS');

-- INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
--     ('BBG_LAND_CORPS_COMBAT_STRENGTH_NATIONALISM', 'Corps', '1'),
--     ('BBG_LAND_CORPS_COMBAT_STRENGTH_NATIONALISM', 'Domain', 'DOMAIN_LAND'),
--     ('BBG_LAND_CORPS_COMBAT_STRENGTH_NATIONALISM', 'Amount', '3'),
--     ('BBG_LAND_ARMIES_COMBAT_STRENGTH_NATIONALISM', 'Corps', '0'),
--     ('BBG_LAND_ARMIES_COMBAT_STRENGTH_NATIONALISM', 'Domain', 'DOMAIN_LAND'),
--     ('BBG_LAND_ARMIES_COMBAT_STRENGTH_NATIONALISM', 'Amount', '3');

-- INSERT INTO RequirementSets(RequirementSetId , RequirementSetType) VALUES
-- 	('BBG_ZULU_NATIONALISM_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL'),
	-- ('BBG_ZULU_MOBILISATION_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');

-- INSERT INTO RequirementSetRequirements(RequirementSetId , RequirementId) VALUES
-- 	('BBG_ZULU_NATIONALISM_REQUIREMENTS', 'BBG_UTILS_PLAYER_HAS_NATIONALISM_REQUIREMENT'),
-- 	('BBG_ZULU_NATIONALISM_REQUIREMENTS', 'BBG_UTILS_PLAYER_HAS_NOT_MOBILISATION_REQUIREMENT'),
	-- ('BBG_ZULU_MOBILISATION_REQUIREMENTS', 'BBG_UTILS_PLAYER_HAS_MOBILISATION_REQUIREMENT');

-- INSERT INTO Requirements(RequirementId , RequirementType, Inverse) VALUES
--     ('BBG_UTILS_PLAYER_HAS_MOBILISATION_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_CIVIC', 0),
-- 	('BBG_UTILS_PLAYER_HAS_NATIONALISM_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_CIVIC', 0),
-- 	('BBG_UTILS_PLAYER_HAS_NOT_MOBILISATION_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_CIVIC', 1);

-- INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
--     ('BBG_UTILS_PLAYER_HAS_MOBILISATION_REQUIREMENT', 'CivicType', 'CIVIC_MOBILIZATION'),
-- 	('BBG_UTILS_PLAYER_HAS_NATIONALISM_REQUIREMENT', 'CivicType', 'CIVIC_NATIONALISM'),
-- 	('BBG_UTILS_PLAYER_HAS_NOT_MOBILISATION_REQUIREMENT' , 'CivicType', 'CIVIC_MOBILIZATION');


-- 16/05/2021: Replace Science Yield by Culture Yield
UPDATE ModifierArguments SET Value='YIELD_CULTURE' WHERE Name='YieldType' AND ModifierID IN
    ('TRAIT_IKANDA_BARRACKS_SCIENCE', 'TRAIT_IKANDA_STABLE_SCIENCE', 'TRAIT_IKANDA_ARMORY_SCIENCE', 'TRAIT_IKANDA_MILITARY_ACADEMY_SCIENCE');

-- citizen yields
UPDATE District_CitizenYieldChanges SET YieldChange=2 WHERE YieldType='YIELD_PRODUCTION'    AND DistrictType='DISTRICT_IKANDA';

-- rewrite the algo of ikanda discount to avoid bug
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_IKANDA' AND ModifierId = 'IKANDA_TRAINED_CORPS_ARMY_DISCOUNT';

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_ZULU_ISIBONGO', 'CCB_ZULU_IKANDA_DISCOUNT_NO_BUG');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_ZULU_IKANDA_DISCOUNT_NO_BUG', 'MODIFIER_CCB_PLAYER_CITIES_CITY_CORPS_ARMY_ADJUST_DISCOUNT', 0, 0, 0, NULL, 'BBG_CITY_HAS_DISTRICT_IKANDA');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_ZULU_IKANDA_DISCOUNT_NO_BUG', 'Amount', '25'), 
('CCB_ZULU_IKANDA_DISCOUNT_NO_BUG', 'UnitDomain', 'DOMAIN_LAND');

INSERT INTO Types (Type, Kind) VALUES 
('MODIFIER_CCB_PLAYER_CITIES_CITY_CORPS_ARMY_ADJUST_DISCOUNT', 'KIND_MODIFIER');
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_CCB_PLAYER_CITIES_CITY_CORPS_ARMY_ADJUST_DISCOUNT', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_CORPS_ARMY_PRODUCTION');