INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','DistrictType','DISTRICT_INDUSTRIAL_ZONE'),
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','Amount','100');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION');

UPDATE ModifierStrings SET Text='LOC_ABILITY_LINCOLN_MELEE_UNITS_COMBAT_DESCRIPTION' WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 16/04/23 +100% toward aqueducs
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'DistrictType', 'DISTRICT_AQUEDUCT'),
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'Amount', '100');

-- 2026/05/10 +2 food for aqueducts
-- BBG_CITY_HAS_DISTRICT_AQUEDUCT see also at sql/CityStates/CityStates.sql
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_LINCOLN', 'CCB_LINCOLN_AQUEDUCT_BONUS_FOOD');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_LINCOLN_AQUEDUCT_BONUS_FOOD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', 0, 0, 0, NULL, 'BBG_CITY_HAS_DISTRICT_AQUEDUCT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_LINCOLN_AQUEDUCT_BONUS_FOOD', 'Amount', '2'), 
('CCB_LINCOLN_AQUEDUCT_BONUS_FOOD', 'YieldType', 'YIELD_FOOD');

-- Base unit discount
-- 14/10/23 removed
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_UNITMAINTENANCEDISCOUNT');

-- 19/06/25 Free units no longer get +5
-- 2025/12/11 +5 back
-- DELETE FROM UnitAbilityModifiers WHERE ModifierId='LINCOLN_MELEE_BUFF';