INSERT INTO Colors (Type, Color) VALUES	
	('COLOR_STANDARD_BBG_GREEN_LT', "0,204,102,255"),
	('COLOR_STANDARD_BBG_ORANGE_DK', "255,178,102,255"),
	('COLOR_STANDARD_BBG_BLUE_MD', "0,0,204,255"),
	('COLOR_STANDARD_BBG_BLUE_LT', "153,204,255,255"),
	('COLOR_STANDARD_BBG_GREY_DK', "60,60,60,255"),
	('COLOR_STANDARD_BBG_RED_DK', "255,0,0,255"),
	('COLOR_STANDARD_BBG_PINK_MD', "204,0,102,255"),
	('COLOR_STANDARD_BBG_GREY_MD', "96,96,96,255");

-- 2025/10/09 colors
-------------------------------------
INSERT OR REPLACE INTO Colors
		(Type,							Color)
VALUES
		("COLOR_STANDARD_CCB_CRIMSON_MD",	"163,33,71,255"),	--#A32147
		("COLOR_STANDARD_CCB_GRAY_LT",		"210,210,210,255"),	--#D2D2D2
		("COLOR_STANDARD_CCB_NAVY_MD",		"29,103,190,255"),	--#1D67BE
		("COLOR_STANDARD_CCB_ORANGE_LT",	"232,149,31,255"),	--#E8951F
		("COLOR_STANDARD_CCB_CRIMSON_DK",	"104,0,103,255"),	--#680067
		("COLOR_STANDARD_CCB_YELLOW_MD",	"239,215,45,255"),	--#EFD72D
		("COLOR_STANDARD_CCB_MAROON_MD",	"160,50,2,255"),	--#A03202
		("COLOR_STANDARD_CCB_AZURE_LT",		"63,155,228,255");	--#248DDF

-- Ba Trieu
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_CCB_CRIMSON_DK', Alt1SecondaryColor='COLOR_STANDARD_CCB_YELLOW_MD' WHERE Type='LEADER_LADY_TRIEU';

-- Gorgo
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_CCB_CRIMSON_MD', Alt2SecondaryColor='COLOR_STANDARD_CCB_GRAY_LT' WHERE Type='LEADER_GORGO';

-- Vercingetorix
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_ORANGE_MD', Alt1SecondaryColor='COLOR_STANDARD_GREEN_DK' WHERE Type='LEADER_SUK_VERCINGETORIX_DLC';
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_ORANGE_MD', Alt1SecondaryColor='COLOR_STANDARD_GREEN_DK' WHERE Type='LEADER_SUK_VERCINGETORIX';

-- Wilfier Laurier
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_BBG_BLUE_MD', Alt2SecondaryColor='COLOR_STANDARD_BBG_BLUE_LT' WHERE Type='LEADER_LAURIER';


-- Wilhelmine
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_CCB_NAVY_MD', Alt2SecondaryColor='COLOR_STANDARD_CCB_ORANGE_LT' WHERE Type='LEADER_WILHELMINA';

UPDATE PlayerColors SET Alt3PrimaryColor='COLOR_STANDARD_CCB_AZURE_LT', Alt3SecondaryColor='COLOR_STANDARD_CCB_ORANGE_LT' WHERE Type='LEADER_WILHELMINA';

-- Spearthrower Owl
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_CCB_MAROON_MD', Alt1SecondaryColor='COLOR_STANDARD_CCB_YELLOW_MD' WHERE Type='LEADER_LIME_TEO_OWL';